name: GitHub Actions Testing

runs:
  using: "composite"
  steps: 
    - name: Healthcheck
      shell: bash
      run: echo "🎉 The job was automatically triggered by event."
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    
    - name: Set PYTHONPATH
      shell: bash
      run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/barbershop/barbershop" >> $GITHUB_ENV

    - name: Install pipx using pip
      shell: bash
      run: pip install pipx

    - name: Install Pipenv
      shell: bash
      run: pipx install --verbose pipenv==2023.12.1

    - name: Install dependencies
      shell: bash
      run: pipenv install --dev --verbose

    - name: Run python tests using Pipenv
      shell: bash
      run: pipenv run test --verbose
      